name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true

    - name: Testing with Maven
      run: mvn test

    - name: Display test result
      run: cat ./target/surefire-reports/*.xml
    
    - name: Check test coverage
      uses: johanvanhelden/gha-clover-test-coverage-check@v1
      id: coverage
      with:
        percentage: "50"
        filename: "./target/surefire-reports/*.xml"

    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Coverage'
        status: ${{ steps.coverage.outputs.coverage }}
        path: ./badges/test-coverage.svg
        color: ${{ steps.coverage.outputs.coveragelines > 75 && 'green' || 'red' }}
