name: CI
on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script 
        run: echo Hello, world!

      - name: Run a two-line script 
        run: echo Hello, Dayo!

      - name: Run a three-line script 
        run: echo Hello, Tobi!

      - name: Run a four-line script 
        run: echo Hello, Canada!

      # Runs a set of commands using the runners shell
      - name: Run a five-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script 
        run: echo Hello, world!

      - name: Run a two-line script 
        run: echo Hello, Dayo!

      - name: Run a three-line script 
        run: echo Hello, Tobi!

      - name: Run a four-line script 
        run: echo Hello, Canada!

      # Runs a set of commands using the runners shell
      - name: Run a five-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

    
