name: CI
on:
  push:
    branches:
    - main

  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUD: "Azure"
      ORG: "SuperHog"
    steps:
      - name: "Run Script ${{env.CLOUD}}"
        run: echo ${{env.CLOUD}}

      # - name: Checkout Repository
      #   uses: actions/checkout@v3
      
      - name: "Login ${{env.CLOUD}}"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true #Ensures you can use the cred in a ps session
    
    
